### ISSUE TITLE
What ODE solver does it use?

### ISSUE THREAD

**Issue by emorell96** [dwd31415/tensorflow-diff-eq#4]
Hi,
I read the code on the .py file, and I wanted to confirm that you are implementing Euler's method using tensorflow's tensors. Am I right? Or which solver does it use to do the actual solving?
Thank you for your help,
Enrique Morell

**Comment by dwd31415** [comment]
Hi Enrique,
that's exactly right, I am using Euler's method here. So it's not really doing anything fancy. Also this package is not really up to date (I did it in 2016 & 2017 mainly), so if you want to get really serious about solving ODEs with TensorFlow I would maybe suggest looking at this [built-in method](https://www.tensorflow.org/probability/api_docs/python/tfp/math/ode/Solver) that has popped up since then. And if you are not bound to TensorFlow I would also suggest having a look at [DifferentialEquations.jl](https://diffeq.sciml.ai/stable/) which is a really great solver (that supports all kinds of differential equations) written in Julia that also is differentiable and has GPU support. 
Best regards, 
Adrian
